### ISSUE TITLE
libbulletc question (DiscreteDynamicsWorld)

### ISSUE THREAD

**Issue by karai17** [AndresTraks/BulletSharpPInvoke#12]
First off I'd like to mention that I think libbulletc should be in its own project as a general purpose C wrapper for Bullet. With that out of the way:

I am using libbulletc to bind Bullet to LuaJIT through FFI. Since Bullet is so huge, I am writing my API on an as-needed basis. I am currently working through Bullet's [Hello World](https://github.com/bulletphysics/bullet3/blob/master/examples/HelloWorld/HelloWorld.cpp) demo to get the most important bits first.

The issue I am having is with `btCollisionWorld_getCollisionObjectArray`. I am unsure about the data that is coming out of this function. The data type is `void *` but I can't iterate or look through it like a normal array. My current method of trying to cast the data seemingly works, but trying to interact with the data makes it quite obvious that there is an issue.

``` lua
function DiscreteDynamicsWorld:getCollisionObjectArray()
    local ret = {} -- Lua table (think of this as an array)

    local num   = bullet.btCollisionWorld_getNumCollisionObjects(self.ct)
    local array = ffi.cast("size_t*", bullet.btCollisionWorld_getCollisionObjectArray(self.ct))

    for i=0, num-1 do
        ret[i+1] = ffi.cast("void*", array) -- Lua is 1-indexed so we need to offset this
        array = array + 1
    end

    return ret
end
```

``` lua
local objectArray = dynamicsWorld:getCollisionObjectArray()

for j, obj in ipairs(objectArray) do
    local body = bt.RigidBody.upcast(obj) -- this returns a void * NULL
    local trans

    if body and body:getMotionState() then
        trans = body:getWorldTransform()
    else
        trans = obj:getWorldTransform()
    end
end
```

If you could explain what this function is supposed to be outputting and how I might be able to cast it to useful data, I would be forever in your debt. <3

**Comment by karai17** [comment]
After spending a few hours watching Dragon Ball and then discussing the issue with some folks, I managed to fix my issue.

``` lua
function DiscreteDynamicsWorld:getCollisionObjectArray()
    local ret = {}

    local num   = bullet.btCollisionWorld_getNumCollisionObjects(self.ct)
    local array = ffi.cast("void*", bullet.btCollisionWorld_getCollisionObjectArray(self.ct))

    for i=0, num-1 do
        ret[i+1] = bullet.btAlignedCollisionObjectArray_at(array, i)
    end

    return ret
end
```

I'll leave this issue open so that my first point can at least be seen, feel free to close it on your own. :)

**Comment by AndresTraks** [comment]
There's a discussion on writing a C wrapper for bullet here: https://github.com/bulletphysics/bullet3/issues/130 so I'll close this one.

It's not yet clear what the best way to do it would be. I just did something that works for P/Invoke in C#, but the C# part of the wrapper hides some of the ugliness of the C library such as the void\* pointers. Maybe it can be done in a nice and type-safe way, but this isn't a priority for me right now. At least you could figure out that it's a btAlignedCollisionObjectArray. :)
