### ISSUE TITLE
Missing libclang.dll in BulletSharpGen project

### ISSUE THREAD

**Issue by Phong13** [AndresTraks/BulletSharpPInvoke#14]
Thanks for all the hard work you have put into this. I have been playing around with BulletSharpPInvoke. I can build the libbulletc and BulletSharpPInvoke projects. But the BulletSharpGen project is missing the libclang.dll file. Could this file be added to the project or a link added explaining where to get it? Thanks.

**Comment by AndresTraks** [comment]
You can get the LLVM installer here: http://llvm.org/releases/download.html
Then just take libclang.dll from the installation directory.

libclang.dll is ~10 MB so I've avoided putting it in the repo, but I'll consider it. The thing is, at the moment, BulletSharpGen is kind of a hack and I don't expect anyone to know how to use it. :)
I do have plans to make it better, but not making any promises.

**Comment by AndresTraks** [comment]
ClangSharp is now handled by NuGet, which also downloads libclang.dll.
