### ISSUE TITLE
compiling bulletsharp

### ISSUE THREAD

**Issue by KakCAT** [AndresTraks/BulletSharpPInvoke#15]
Hi,

is there a place where I can get instructions on how to compile BulletSharp for Windows and Windows Phone?

In bulletSharpGen there's a missing  DLL, libclang.dll . Removing it compiles, but I don't know what exactly does this project.

BulletSharpPInvoke project seems to compile well, but I suppose I can't use the DLL as is, I probably need the bullet library.

I also suppose that I can get the library compiling the libbulletc project, but that project is not working for me at all. There are includes like BulletCollision/CollisionDispatch/btCollisionWorld.h , however the src directory is everything in a single directory (btCollisionWorld.h is there, but it's not found because of the path)

Regards!
Kak

**Comment by AndresTraks** [comment]
Yes, here it is: https://github.com/AndresTraks/BulletSharpPInvoke/wiki/Build-Instructions
Windows Phone is not supported though. You'll have to use [Bullet-XNA](https://github.com/xexuxjy/bullet-xna) or something similar.

BulletSharpGen is probably not useful for you. It generates most of the BulletSharp and libbulletc code from Bullet sources.

libclang.dll is a large file, so it's not in the repository. You'll have to download it from http://llvm.org if you need it.

**Comment by KakCAT** [comment]
Thanks for your answer, I've been able to compile it and run the examples.

WP7 was an XNA-only device, so BulletSharp won't run there for sure, but in theory BulletSharp should run on Windows Phone 8.1 . I'm not so sure about WP8 because it had no PInvoke support but I think there are workarounds to that when you can compile the source anew.

I don't know if I'll be smart enough to get to this point though ^^ 

EDIT: found a sample mixing C# and C++ for WP8, so it may be possible after all
http://www.jarredcapellman.com/2012/11/03/how-to-get-c-winrt-in-a-windows-phone-8-application/
