### ISSUE TITLE
Missing functions in libbulletc

### ISSUE THREAD

**Issue by Phong13** [AndresTraks/BulletSharpPInvoke#17]
Hi Andres,

First I would like to say a big thank you for all the work you have put into this. I have been using it very successfully in Unity3d for the most part it works great! I am using it for the physics the tether in my game EVA Infinity with no problems and have started an open source project to create high quality wrappers for the physics in Unity3d. Everyone who has looked at it so far is very excited.

I have been trying to get it working on iOS which requires that the libbulletc library be statically linked (Unity first translated the C# IL code to C++). When I do this 103 linker errors are generated. It appears that there are wrapper methods in the C# that are calling methods that do not exist in libbulletc. For example PersistentManifold.cs tries to call external method btPersistentManifold_delete in the dispose method. btPersistentManifold_wrap.cpp and .h do not contain the method  btPersistentManifold_delete. Similarly the C# code has a whole class for: BT_BOX_BOX_TRANSFORM_CACHE which has no corresponding exported class in libbulletc.

I started working my way through these removing references to the stuff that didn't exist in libbulletc. Some of the missing functions seem harmless or to have been intentionally commented out (such as SoftBodySolver.optimize). But some of them such as btPersistentManifold_delete seems to be fairly serious omission that I think would break using the PersistentManifild class. Also removing these is a big job and I don't want to repeat it when BulletSharpPInvoke is updated. Are these problems with the wrapper generator? Would it be better to fix them there?

Please let me know if you have any thoughts on the best approach to take with this. 

Thanks.

**Comment by AndresTraks** [comment]
Thanks for working on the Unity port! It's often been requested, but I never got around to playing with it.

The stuff that's commented out is mostly code that either needs more work or code that I'm not sure needs to be exposed to the C# API. And with PersistentManifold, I'm not sure if a user should be able to create their own manifolds considering that manifolds are typically handled internally, so a delete function might not be necessary. I'm currently working to look through all these cases and handling them in BulletSharpGen. But for now, the code can be a bit messy and inconsistent in some places.

I've removed the BT_BOX_BOX_TRANSFORM_CACHE class and added a few missing delete functions. If you send me the error log, I can probably fix the remaining errors quickly. I didn't realise the missing functions would cause errors, but I don't have iOS tools available, so I can't properly review this.

**Comment by Phong13** [comment]
Hi Andres, thanks for looking at this. I have attached a file with the linker errors. The names of the functions look funny because they are the C# wrappers converted to C++ by Unity's il2cpp tool but it is fairly straightforward to see what function and class they belonged to. I see your point with the PersistentManifold. Let me know if there is anything I can provide that would help.

[xcodeLinkerErrors.txt](https://github.com/AndresTraks/BulletSharpPInvoke/files/110684/xcodeLinkerErrors.txt)

**Comment by AndresTraks** [comment]
Okay, all the errors should be gone now, except I don't know what the matter is with btSoftBody_RayFromToCaster_rayFromToTriangle. It seems to be exported properly in libbulletc on Windows.

**Comment by Phong13** [comment]
Thanks Andres, I will try it out as soon as I get back to my Mac on Tuesday.

On Sun, Jan 31, 2016 at 11:57 AM, Andres Traks notifications@github.com
wrote:

> Okay, all the errors should be gone now, except I don't know what the
> matter is with btSoftBody_RayFromToCaster_rayFromToTriangle. It seems to be
> exported properly in libbulletc on Windows.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AndresTraks/BulletSharpPInvoke/issues/17#issuecomment-177597425
> .

## 

Ian Deane
DigitalOpus http://digitalopus.ca
Twitter: @DigitalOpus https://twitter.com/DigitalOpus
Vote for my new game EVA Infinity on Steam Greenlight
http://steamcommunity.com/sharedfiles/filedetails/?id=535754554!
