### ISSUE TITLE
ConvexHullShape(float[] ) error

### ISSUE THREAD

**Issue by Phong13** [AndresTraks/BulletSharpPInvoke#18]
Hi Andres, thanks again for all your work on this. I have come across another bug. Creating a convex hull only works for very simple shapes like a cube or a tet. For larger shapes like a capsule mesh it explodes.

I was able to debug into the libbulletc.dll and it appears the problem is the "striding" parameter. The Bullet C++ code for the btConvexHullShape constructor looks like this:

```
btConvexHullShape ::btConvexHullShape (const btScalar* points,int numPoints,int stride) : btPolyhedralConvexAabbCachingShape ()
{
    m_shapeType = CONVEX_HULL_SHAPE_PROXYTYPE;
    m_unscaledPoints.resize(numPoints);

    unsigned char* pointsAddress = (unsigned char*)points;

    for (int i=0;i<numPoints;i++)
    {
        btScalar* point = (btScalar*)pointsAddress;
        m_unscaledPoints[i] = btVector3(point[0], point[1], point[2]);
        pointsAddress += stride;
    }

    recalcLocalAabb();

}
```

The "pointsAddress" pointer is sizeof(unsigned char) and is being incremented by the stride which is 3. I think the stride needs to be 3 \* sizeof(float) for this to work correctly. I changed the code on the C# side to:

`
public ConvexHullShape(float[] points)
            : this(points, points.Length, 3 * sizeof(float))
        {
        }
`
And the problem was fixed. Thanks again.

**Comment by AndresTraks** [comment]
Yes, you're right, the stride should be in bytes. Fixed it. Thanks!
