### ISSUE TITLE
Errors in btManifoldPoint_wrap.cpp

### ISSUE THREAD

**Issue by Phong13** [AndresTraks/BulletSharpPInvoke#19]
The build is broken in the latest version of BulletSharpPInvoke libbulletc project. File btManifoldPoint_wrap.cpp refers to variables m_contactCFM and m_contactERP. but the class btManifoldPoint does not contain these members.

**Comment by AndresTraks** [comment]
They were added to bullet3 recently:
https://github.com/bulletphysics/bullet3/commits/master/src/BulletCollision/NarrowPhaseCollision/btManifoldPoint.h

Update your repository. :)

**Comment by Phong13** [comment]
Ahhh. Silly me. Face palm.
