### ISSUE TITLE
Possible bug with arrays decorated with [out] attribute

### ISSUE THREAD

**Issue by Phong13** [AndresTraks/BulletSharpPInvoke#20]
I have been working with BulletSharpPInvoke in Unity (uses Mono instead of .Net). Overall the experience has been great but I have had problems with methods like:

btSoftBody_wrap.cpp 
getLinkVertexData(SoftBody\* obj, btScalar\* array)

On windows these sporadically crash. Most of the time they work. If I switch to getting positions from the nodes then it works all the time.

On iOS this method fails with memory bad access errors every time.

I switched the decorator on the array from [Out] to [In,Out]. This fixed the problem.  The MSDN documentation suggests that [In, Out] is needed to receive data by passing an array into a method. https://msdn.microsoft.com/en-us/library/hk9wyw21(v=vs.110).aspx

This may be a difference between Mono and .Net.

**Comment by AndresTraks** [comment]
Unfortunately I don't have an iOS target to test against and never had a problem with this on Windows, but the solution does make sense. Even though we only care about the data going out, we're still using the memory that goes in. And the documentation also suggests that the In parameter should be there in any case.

I'm actually just in the middle of cleaning up the In/Out attributes, so I'll get to this soon. Probably wouldn't have caught this bug though, so thanks!

**Comment by AndresTraks** [comment]
I replaced [Out] with [In, Out] for those methods, so this should be fixed.
