### ISSUE TITLE
Bug with ConvexHullShape

### ISSUE THREAD

**Issue by Phong13** [AndresTraks/BulletSharpPInvoke#21]
The second constructor for ConvexHullShape

```
    public ConvexHullShape(float[] points)
        : this(points, points.Length, 3 * sizeof(float))
    {
```

Should be:

```
    public ConvexHullShape(float[] points)
        : this(points, points.Length/3, 3 * sizeof(float))
    {
```

The 2nd argument, number of points, needs to be length of the float array divided by three.

**Comment by AndresTraks** [comment]
Fixed in https://github.com/AndresTraks/BulletSharpPInvoke/commit/ceac5daec495b2b418c17484036efda5874ff0da. Thanks!
