### ISSUE TITLE
libbulletc: use #ifdef __cplusplus in C headers

### ISSUE THREAD

**Issue by CapsAdmin** [AndresTraks/BulletSharpPInvoke#26]
I'd make a pull request but I'm unable to build BulletSharpGen with mono.

**Comment by AndresTraks** [comment]
Good point.
BulletSharpGen got broken during some refactoring and it's still in prototype stage, so it can't generate all of the wrapper code. The __cplusplus definition is something that BulletSharpGen could be made to generate, but some work is needed to make BulletSharpGen not crash and then add the __cplusplus definitions.

**Comment by AndresTraks** [comment]
I added the #ifdef __cplusplus guards manually.
