### ISSUE TITLE
Is it possible to build BulletSharpGen with mono?

### ISSUE THREAD

**Issue by CapsAdmin** [AndresTraks/BulletSharpPInvoke#28]
I'm not experienced with this but with some googling around I got this far:

* install mono
* get `NuGet.exe` and `Microsoft.Build.dll` and put them in `BulletSharpPInvoke/BulletSharpGen/packages/*`
* run `mono --runtime=v4.0 NuGet.exe install clang.sharp` in the packages folder
* xbuild BulletSharpGen.sln

I got some warnings and errors related to the framework version `v4.6.1` not being supported so I changed it to `v4.5` in BulletSharpGen.csproj assuming it was just some default target when you created the project.

Now I'm stuck at these errros

```
DotNet/SymbolMapping.cs(1,17): error CS0234: The type or namespace name `CodeAnalysis' does not exist in the namespace `Microsoft'. Are you missing an assembly reference?
DotNet/SymbolMapping.cs(2,17): error CS0234: The type or namespace name `CodeAnalysis' does not exist in the namespace `Microsoft'. Are you missing an assembly reference?
DotNet/SymbolMapping.cs(54,9): error CS0246: The type or namespace name `Script' could not be found. Are you missing an assembly reference?
```

If you want to support this on linux and mac this information might give you some hints.

**Comment by AndresTraks** [comment]
I've only tried BulletSharp itself in Mono. BulletSharpGen is just a helper for generating code, so it has some exotic dependencies like the Roslyn scripting engine. I think Nuget and Mono have trouble recognizing some of the newer .NET 4.5 and 4.6 packages, but I don't know more than you do.
Anyway, BulletSharpGen is kinda broken at the moment and Bullet hasn't had many code changes, so I haven't had the motivation to fix it. So I don't think it's worth getting it to work for now. Maybe when I have more time.

**Comment by AndresTraks** [comment]
I've since replaced BulletSharpGen with a more general generator project, but I'm not actively working on either of them until necessary.
https://github.com/AndresTraks/DotNetWrapperGen

Thanks for the report!
