### ISSUE TITLE
Cannot set both pre and post-tick callbacks

### ISSUE THREAD

**Issue by Inverness** [AndresTraks/BulletSharpPInvoke#29]
Bullet lets you set both pre and post-tick callbacks, but BulletSharp does not allow this.

Bullet's implementation: https://github.com/bulletphysics/bullet3/blob/master/src/BulletDynamics/Dynamics/btDynamicsWorld.h#L111

A use case: https://github.com/bulletphysics/bullet3/blob/master/examples/MultiThreadedDemo/CommonRigidBodyMTBase.cpp#L792

**Comment by AndresTraks** [comment]
It is implemented.
https://github.com/AndresTraks/BulletSharpPInvoke/blob/master/BulletSharpPInvoke/Dynamics/DynamicsWorld.cs#L160

Edit: Oh, right, you can't have both at the moment. I'll fix that.

**Comment by AndresTraks** [comment]
Fixed in https://github.com/AndresTraks/BulletSharpPInvoke/commit/3bc185f64f65332dfdd4a951c5ad47a2b5027d1c.
