### ISSUE TITLE
Error compiling demos

### ISSUE THREAD

**Issue by publicENEMY** [AndresTraks/BulletSharpPInvoke#3]
Error   2   Cannot implicitly convert type 'BulletSharp.CollisionFilterGroups' to 'short'. An explicit conversion exists (are you missing a cast?)  e:\Users\iJam\Source\Repos\BulletSharpPInvoke\BulletSharpPInvoke\demos\CharacterDemo\CharacterDemo.cs   157 38  CharacterDemo

**Comment by AndresTraks** [comment]
This was fixed just when the issue was opened.
