### ISSUE TITLE
CMake -G "Visual Studio 15 2017 Win64" create endless recursive dir

### ISSUE THREAD

**Issue by patricksuo** [AndresTraks/BulletSharpPInvoke#32]
Did I miss sth?

**Comment by AndresTraks** [comment]
I haven't seen this error.
What directories are created?
Which version of CMake is it?
Did you try CMake-gui?

**Comment by patricksuo** [comment]
> I haven't seen this error.
> What directories are created?
 `bullet\bullet\bullet\...`

> Which version of CMake is it?
cmake version 3.9.1

> Did you try CMake-gui?


I can't reproduce this morning.
