### ISSUE TITLE
Double precision support

### ISSUE THREAD

**Issue by AndresTraks** [AndresTraks/BulletSharpPInvoke#36]
TODO:
Create a separate branch where btScalars are double instead of float in the managed assembly.

**Comment by AndresTraks** [comment]
Initial code: https://github.com/AndresTraks/BulletSharpPInvoke/tree/double-precision

**Comment by zorkind** [comment]
Is this branch updated i really need to use Doubles :(

**Comment by AndresTraks** [comment]
I merged the master branch to the double-precision branch.
There weren't too many significant changes.

**Comment by zorkind** [comment]
Good deal Andres, i was finally able to make it work, i think it was just me being dumb.

:)
