### ISSUE TITLE
Can't CMake on Windows

### ISSUE THREAD

**Issue by dreding** [AndresTraks/BulletSharpPInvoke#37]
Try from console and gui. Always get this error:

Selecting Windows SDK version 10.0.15063.0 to target Windows 10.0.14393.
The C compiler identification is MSVC 19.10.25019.0
The CXX compiler identification is MSVC 19.10.25019.0
Selecting Windows SDK version 10.0.15063.0 to target Windows 10.0.14393.
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe
CMake Error: The source directory "OUTPUT_VARIABLE" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
CMake Error at C:/Program Files/CMake/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:37 (try_compile):
  Failed to configure test project build system.
Call Stack (most recent call first):
  CMakeLists.txt:2 (PROJECT)

Configuring incomplete, errors occurred!
See also "/CMakeFiles/CMakeOutput.log".

No log file in this directory.

**Comment by AndresTraks** [comment]
Do you have permission to write to the "Where to build the binaries:" folder?

**Comment by dreding** [comment]
Yes, GUI and console was run from administrator also.

**Comment by dreding** [comment]
On Ubuntu all works perfectly.

**Comment by RenzoCoppola** [comment]
I'm a noob with this cmake stuff... but, it also didnt work for me using cmake-gui. it created an almost endless folder hierarchy

**Comment by AndresTraks** [comment]
See https://github.com/AndresTraks/BulletSharpPInvoke/issues/39#issuecomment-362056042 (and #32).
CMake can't with find where Bullet is located and crashes when testing some common locations. It then creates a bunch of bullet/bullet/bullet folders for whatever reason.
The easiest thing to do is to clone the bullet3 and BulletSharpPInvoke repositories into the same directory, so you have directories with these names:
* [root_folder]
  * bullet3
    * CMakeLists.txt
    * ...
  * BulletSharpPInvoke
    * CMakeLists.txt
    * ...

And then continue generating the CMake solutions as in the [build instructions](https://github.com/AndresTraks/BulletSharpPInvoke/wiki/Build-Instructions).

**Comment by AndresTraks** [comment]
Sorry, I meant:
* [root_folder]
  * bullet3
    * CMakeLists.txt
    * ...
  * BulletSharpPInvoke
    * BulletSharp
    * libbulletc
      * CMakeLists.txt
      * ...
