### ISSUE TITLE
Does not compile out-of-the-box using bullet 2.87

### ISSUE THREAD

**Issue by Krakean** [AndresTraks/BulletSharpPInvoke#40]
C:\DevProjects\RTSProject\3rdParty\BulletSharp_LibC\src\btBulletFile_wrap.cpp(1): fatal error C1083: Cannot open include file: '../BulletFileLoader/btBulletFile.h': No such file or directory
C:\DevProjects\RTSProject\3rdParty\BulletSharp_LibC\src\btBulletWorldImporter_wrap.cpp(2): fatal error C1083: Cannot open include file: '../BulletFileLoader/btBulletFile.h': No such file or directory
C:\DevProjects\RTSProject\3rdParty\BulletSharp_LibC\src\btBulletXmlWorldImporter_wrap.cpp(2): fatal error C1083: Cannot open include file: 'btBulletXmlWorldImporter.h': No such file or directory
C:\DevProjects\RTSProject\3rdParty\BulletSharp_LibC\src\btBulletWorldImporter_wrap.cpp(3): fatal error C1083: Cannot open include file: 'btBulletWorldImporter.h': No such file or directory
C:\DevProjects\RTSProject\3rdParty\BulletSDK\src\BulletXmlWorldImporter\btBulletXmlWorldImporter.h(41): fatal error C1083: Cannot open include file: 'btWorldImporter.h': No such file or directory
C:\DevProjects\RTSProject\3rdParty\BulletSharp_LibC\src\btWorldImporter_wrap.cpp(6): fatal error C1083: Cannot open include file: 'btWorldImporter.h': No such file or directory

Yes, these errors can be fixed manually, but still...

**Comment by AndresTraks** [comment]
The reference to Bullet that you removed in #39 is required.
