### ISSUE TITLE
Simplest example using BulletSharp.dll

### ISSUE THREAD

**Issue by petrasvestartas** [AndresTraks/BulletSharpPInvoke#42]
I am am trying to find an example to run bullet physics on stand alone application.

I just want to initialize a solver add few objects to BulletSharp solver.
Run a few hundread iterations and get the geometry.

Is it possible to get an example without any windows forms or UI?

**Comment by dimonkov** [comment]
Yep,
just create a good old console application, add BulletSharp as nuget, and create something like this:
```csharp
using System;
using BulletSharp;
using BulletSharp.Math;


class Program
{
    static void Main(string[] args)
    {
        using (var colConfiguration = new DefaultCollisionConfiguration())
        {
            using (var colDispatcher = new CollisionDispatcher(colConfiguration))
            {
                //Pick broadphase algorithm
                using (var broadphase = new DbvtBroadphase())
                {
                    //Create a collision world of your choice, for now pass null as the constraint solver
                    using (var colWorld = new DiscreteDynamicsWorld(colDispatcher, broadphase, null, colConfiguration))
                    {
                        //Create the object shape - A 10x1x10 box in this case
                        using (var groundShape = new BoxShape(5f, 0.5f, 5f))
                        {
                            //Use that shape to prepare object construction information
                            //Initial position can be supplied into Motion state's constructor
                            using (var groundBodyConstructionInfo =
                                new RigidBodyConstructionInfo(0f, new DefaultMotionState(), groundShape))
                            {
                                //Create rigidbody(a physics object that can be added to the world and will collide with other objects)
                                using (var ground = new RigidBody(groundBodyConstructionInfo))
                                {
                                    //Register the object in the world for it to interact with other objects
                                    colWorld.AddCollisionObject(ground);

                                    //Create a shape for our ball - a sphere with radius of 2
                                    using (var ballShape = new SphereShape(2f))
                                    {

                                        //Ball creation info - an object with a mass of 5 and placed 10 units up on Y axis
                                        using (var ballConstructionInfo = new RigidBodyConstructionInfo(5f,
                                            new DefaultMotionState(Matrix.Translation(0f, 10f, 0f)), ballShape))
                                        {
                                            //Create the ball object with supplied parameters
                                            using (var ball = new RigidBody(ballConstructionInfo))
                                            {

                                                //Add ball to the world
                                                colWorld.AddCollisionObject(ball);

                                                //Just for fun, log the ball's position
                                                Console.WriteLine(ball.MotionState.WorldTransform.Origin);

                                                //Prepare simulation parameters, try 25 steps to see the ball mid air
                                                var simulationIterations = 125;
                                                var simulationTimestep = 1f / 60f;

                                                //Step through the desired amount of simulation ticks
                                                for (var i = 0; i < simulationIterations; i++)
                                                {
                                                    colWorld.StepSimulation(simulationTimestep);
                                                }

                                                //Log the ball's position after simulation happened
                                                //It falls down with each step and with enough steps will rest on the ground
                                                Console.WriteLine(ball.MotionState.WorldTransform.Origin);
                                            }
                                        }
                                    }

                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by petrasvestartas** [comment]
Dear Dimonkov,

Thank you very much for a reply.

What is the reason to use "using" after each declaration?
Is it because of garbage collector to remove object as soon as it is not needed?
Would it also work if using is not added?

Since I am quite new to Bullet Sharp, what would be the way to extract coordinates of more complicated meshes than a sphere? Is it working through transformations, or it is possible to extract vertices of meshes at each iteration?

**Comment by dimonkov** [comment]
Each BulletSharp object (as I understand it) holds unmanaged resources, 
and because garbage collection happens whenether runtime decides to, I prefer to dispose unused resources ASAP.
I guess it would also work without it, however if something implements IDisposable - it's probably for a reason.

Each object has a world transform matrix4x4 that contains translation, rotation and scale data for that object.
For extracting shape data - I suggest you to take a look at [Mesh factory](https://github.com/AndresTraks/BulletSharpPInvoke/blob/master/BulletSharp/demos/DemoFramework/Graphics/MeshFactory.cs).

Just a little note - shapes and rigidbodies are two different concepts:
Shapes define an absolute shape of an object, whereas rigidbody uses the shape data - it has it's own position, rotation and scale in the world.
One shape can be even shared among several rigidbodies to save memory.

Once you have the vertex data, you'll have to apply Rigidbody's transformation to each of them if you want to know the true world position of each vertex.

@AndresTraks , please correct me If I'm wrong. I'm not too good with transformations.

**Comment by petrasvestartas** [comment]
I tried the code today on my visual studio.

I get error regarding libbulletc.dll. I thought I would only need to reference BulletSharp.dll.

Could you help me to solve this?

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libbulletc': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at BulletSharp.UnsafeNativeMethods.btDefaultCollisionConfiguration_new()
   at BulletSharp.DefaultCollisionConfiguration..ctor() in D:\Processing\BulletSharpPInvoke-master\BulletSharp\Collision\DefaultCollisionConfiguration.cs:line 93
   at ConsoleApp1.Program.Main(String[] args) in \\files0\data\vestarta\my documents\visual studio 2017\Projects\ConsoleApp1\ConsoleApp1\Program.cs:line 15

**Comment by petrasvestartas** [comment]
Oh I did not see that I had to use CMAKE, it seems to be built correctly.


Is it this .dll that I need to use together with BulletSharp.dll?

![built](https://user-images.githubusercontent.com/18013985/38925551-3eca67d0-4300-11e8-8485-4ae281345a3c.png)

**Comment by dimonkov** [comment]
I recommend you to add BulletSharp to your project using nuget - it will install all needed dlls.

And yes you need libbulletc

**Comment by petrasvestartas** [comment]
After building everything according to instructions I get this error:

Unhandled Exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at BulletSharp.UnsafeNativeMethods.btDefaultCollisionConfiguration_new()
   at BulletSharp.DefaultCollisionConfiguration..ctor()
   at ConsoleApp1.Program.Main(String[] args) in \\files0\data\vestarta\my documents\visual studio 2017\Projects\ConsoleApp1\ConsoleApp1\Program.cs:line 11


![build](https://user-images.githubusercontent.com/18013985/38926060-ae355886-4301-11e8-8f81-78b7db8ba59c.png)

**Comment by petrasvestartas** [comment]
Dimonkov after installing Nuget package it works perfectly.

Thank you very much:)

**Comment by petrasvestartas** [comment]
I just tried to do the same procedure to my own application.
I installed BulltetSharp via nuget.

This time I get the same error:
System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

Och I just want to make a simple test...

**Comment by dimonkov** [comment]
Bad Image probably means wrong architecture.
Are you building 64 bit app?

**Comment by dimonkov** [comment]
Check your project settings.

![image](https://user-images.githubusercontent.com/1696484/38929187-32a8b862-4314-11e8-9232-7a82bae9e94e.png)
If you target x64 ("Prefer 32-bit" is unchecked) you'll need to delete the libbulletc.dll in your output folder
and rename "libbulletc-windows-x64.dll" to "libbulletc.dll".

I think it is the only workaround.

**Comment by petrasvestartas** [comment]
Thanks, now it loads.

It was also by default configured to AnyCPU, I removed 86x and left 64bit version.
Now the app is compiled without error.

Now I will try to display sphere:)

**Comment by petrasvestartas** [comment]
The sphere is being display woohoo. 
What would be the way to add gravity force or other constraint to move that sphere?

**Comment by dimonkov** [comment]
Gravity should be enabled by default.
Make sure you pass weight for RigidbodyConstructionInfo.

**Comment by petrasvestartas** [comment]
I changed the mass of object to 1 and it moves yeee

new RigidBodyConstructionInfo(**1**f, new DefaultMotionState(), groundShape)) {}

It took a long time to compile and run, but definetely worth it.

It would be nice if there would much more examples like this.

Thank you Dimonkov alot.

**Comment by dimonkov** [comment]
No problem.

**Comment by petrasvestartas** [comment]
May I ask how can I modify the code in order to add an array of BoxShape objects falling down on the ground as screenshot below.

When I try to declare an array of BoxShapes within using statement:
  using (BoxShape[] ballShape = new BoxShape[2] { new BoxShape(1, 2, 3), new BoxShape(1, 2, 3) }) { ... }

I get error: CS1674	'BoxShape[]': type used in a using statement must be implicitly convertible to 'System.IDisposable'	


![array](https://user-images.githubusercontent.com/18013985/38934245-944103a2-431b-11e8-8e84-2c84116e82c9.png)

![addingelement](https://user-images.githubusercontent.com/18013985/38934255-99987fc4-431b-11e8-927b-bbf9f956f56f.png)

**Comment by dimonkov** [comment]
First of all - you cannot dispose because arrays are not diposable. You'll have to iterate over the array and dispose each object.

You don't want to create multiple shapes.
Again - shapes define geometry, they are not individual objects.
Thus, you actually want to create multiple rigidbodies with different transformations, possibly sharing the same shape.

**Comment by petrasvestartas** [comment]
If I add rigid bodies referencing the same shape like this:

    for (int i = 0; i < 10; i++) {

       using (var ballConstructionInfo = new RigidBodyConstructionInfo(5f, new 
       DefaultMotionState(BulletSharp.Math.Matrix.Translation(0f, i * 10f, 0f)), ballShape)) {

      using (RigidBody ball = new RigidBody(ballConstructionInfo)) {

      colWorld.AddCollisionObject(ball);

     }
    }
    }

then run simulation for n times.

How can I retrieve each ball position/transformation matrix at the later step, as all rigid bodies were disposed in for loop in each iteration?

**Comment by dimonkov** [comment]
You are disposing them right after you add them, so they don't even make their way through a single simulation step.

What you want to do instead, is:
Declare a List<IDisposable> before object creation (in this example objectsToDispose);
Add every created rigidbody to this list;
After you are done with them just iterate over your list and call dispose on them;

Like so:

```csharp
foreach(var obj in objectsToDispose)
    obj.dispose();
```

Please note - DO NOT dispose objects that are still in use.
For example if you wish to destroy a couple of objects in the world and continue with the simulation, 
you have to safely remove each of them from the world by calling 
```cssharp 
colWorld.RemoveRigidbody(obj); 
```
and only then dispose.

**Comment by petrasvestartas** [comment]
I did this small simulation test and disposed objects according to your description:
https://www.youtube.com/watch?v=2rNcPNdd4gU&feature=youtu.be

What do I miss, because boxes do not rotate?

I checked boxes[i].MotionState.WorldTransform at each iteration and the matrix numbers are only changing at translation but not rotation.

I attached also full code:
[Test.txt](https://github.com/AndresTraks/BulletSharpPInvoke/files/1924836/Test.txt)

**Comment by dimonkov** [comment]
Forgot to mention you have to calculate local inertia in RigidbodyConstructionInfo.
That will allow objects to rotate.

So change your RigidbodyConstructionInfo initialization to this:
```cssharp
for (int i = 0; i < 10; i++)
    ballConstructionInfo.Add(new RigidBodyConstructionInfo(5f,
    new DefaultMotionState(
    BulletSharp.Math.Matrix.Translation(0f, 10 + i * 5f, i * 3.7f)),
    boxShape,boxShape.CalculateLocalInertia(5f)));
```

Note - mass passed into CalculateLocalInertia is the same as Rigidbody's mass.

**Comment by petrasvestartas** [comment]
Thank you very much:)
It works perfectly:
https://vimeo.com/265424382

**Comment by AndresTraks** [comment]
Yes, all objects that have the Dispose method should be disposed once they are no longer in use.
The using block is a good way to not forget to dispose objects, but it is better suited for objects with a short lifetime, like using a RigidBodyConstructionInfo to create a body:
```
RigidBody body;
using (var bodyInfo =
    new RigidBodyConstructionInfo(mass, motionState, shape, inertia))
{
    body = new RigidBody(bodyInfo);
}
```
The equivalent of the using block is to just call Dispose:
```
var bodyInfo =
    new RigidBodyConstructionInfo(mass, motionState, shape, inertia))
RigidBody body = new RigidBody(bodyInfo);
bodyInfo.Dispose();
```
In a larger program, it's better to keep objects with a longer lifetime as class variables of the physics component so you don't have to go crazy with indentation :) So something like:
```
public sealed class BulletPhysicsGHComponent : IDisposable
{
    private DefaultCollisionConfiguration _configuration;
    private CollisionDispatcher _dispatcher;
    private DbvtBroadphase _broadphase;
    private DiscreteDynamicsWorld _world;
    private IList<CollisionShape> _shapes = new List<CollisionShape>();
    private bool _isDisposed = false;

    public IList<RigidBody> Bodies = new List<RigidBody>();

    public BulletPhysicsGHComponent()
    {
        _configuration = new DefaultCollisionConfiguration();
        _dispatcher = new CollisionDispatcher(_configuration);
        _broadphase = new DbvtBroadphase();
        _world = new DiscreteDynamicsWorld(_dispatcher, _broadphase, null, _configuration);

        var groundShape = new BoxShape(5, 0.5f, 5);
        _shapes.Add(groundShape);
        var ground = CreateStaticBody(groundShape);
        Bodies.Add(ground);
        _world.AddRigidBody(ground);

        var boxShape = new BoxShape(1, 2, 3);
        _shapes.Add(boxShape);

        var box = CreateDynamicBody(groundShape, 5, Matrix.Translation(0, 10, 0));
        Bodies.Add(box);
        _world.AddRigidBody(box);

        var box2 = CreateDynamicBody(groundShape, 5, Matrix.Translation(0, 15, 0));
        Bodies.Add(box2);
        _world.AddRigidBody(box2);
    }

    public void StepSimulation()
    {
        _world.StepSimulation(1 / 60.0f);
    }

    public void Dispose()
    {
        if (_isDisposed) return;
        foreach (var body in Bodies)
        {
            _world.RemoveRigidBody(body);
            body.Dispose();
        }
        foreach (var shape in _shapes)
        {
            shape.Dispose();
        }
        _world.Dispose();
        _broadphase.Dispose();
        _dispatcher.Dispose();
        _configuration.Dispose();
        _isDisposed = true;
    }

    private static RigidBody CreateStaticBody(CollisionShape shape)
    {
        using (var bodyInfo = new RigidBodyConstructionInfo(0, null, shape))
        {
            return new RigidBody(bodyInfo);
        }
    }

    private static RigidBody CreateDynamicBody(CollisionShape shape, float mass, Matrix startTransform)
    {
        using (var bodyInfo = new RigidBodyConstructionInfo(mass, new DefaultMotionState(startTransform), shape, shape.CalculateLocalInertia(mass)))
        {
            bodyInfo.StartWorldTransform = startTransform;
            return new RigidBody(bodyInfo);
        }
    }
}
```
And then you could use the physics component like this;
```
using (var physics = new BulletPhysicsGHComponent())
{
    for (int i = 0; i < 1000; i++)
    {
        physics.StepSimulation();
        foreach (var body in physics.Bodies)
        {
            // Get object transform from body.WorldTransform
        }
    }
}
```

**Comment by petrasvestartas** [comment]
Dear Andres Traks,

Thank you, it allows to split the code into solver and interface for preivewing geometry in a clean way.

Since I am learning this nice library. I have more questions.

I would like to ask what is causing intersection when objects are colliding:
https://www.youtube.com/watch?v=vCfBoj5vt4w&feature=youtu.be

When inertia is turned on, the intersection during collision is visible a bit more.
Is it possible to control this behavior?

I attached the code. which is almost the same as you showed.
[Solver.txt](https://github.com/AndresTraks/BulletSharpPInvoke/files/1927401/Solver.txt)
[BulletPhysicsGHComponent.txt](https://github.com/AndresTraks/BulletSharpPInvoke/files/1927404/BulletPhysicsGHComponent.txt)

**Comment by petrasvestartas** [comment]
Also wondering how to replace this using statement:

                using (var solver = new BulletPhysics.Solver(boxDimensions, positions, inertia)) {
                    for (int i = 0; i < iterations; i++) {
                        solver.StepSimulation();
                      ...
            }
          }

I would like to trigger StepSimulation outside using scope wihtout using for loop.
But current setup deletes solver after some iterations, while I would like to keep it running for a while in Rhino software I am using.

Wondering how unsafe it would be...

What I would like to do is:

1) Declare solver without using 
 BulletPhysics.Solver solver = new BulletPhysics.Solver(boxDimensions, positions, inertia);

2) Trigger simulation through application I am using
  solver.StepSimulation();

3) Then how I could dispose both solver and object inside it?
Currently I am disposing them like this solver.Dispose();
But how to dispose whole solver?

**Comment by AndresTraks** [comment]
I suspect that matrices in Rhino have different element order (https://en.wikipedia.org/wiki/Row-_and_column-major_order) than BulletSharp.
The translation part of the matrix has already been transposed and the translation seems to be correct in the video. So try also transposing the rotational part of the matrix.
```
t.M00 = body.WorldTransform.M11;//Scale
t.M01 = body.WorldTransform.M21;
t.M02 = body.WorldTransform.M31;
t.M03 = body.WorldTransform.M41;//Translation Rhino X 

t.M10 = body.WorldTransform.M12;
t.M11 = body.WorldTransform.M22;//Scale
t.M12 = body.WorldTransform.M32;
t.M13 = body.WorldTransform.M42;//Translation Rhino Y

t.M20 = body.WorldTransform.M13;
t.M21 = body.WorldTransform.M23;
t.M22 = body.WorldTransform.M33;//Scale
t.M23 = body.WorldTransform.M43;//Translation Rhino Z

t.M30 = 0;
t.M31 = 0;
t.M32 = 0;
t.M33 = 1;//Scale
```
Since matrices coming from Bullet never have scaling or shearing (it is not necessary in physics simulations), you can assume that (M14, M24, M34, M44) is always (0, 0, 0, 1).

**Comment by AndresTraks** [comment]
> Then how I could dispose both solver and object inside it?
> Currently I am disposing them like this solver.Dispose();
> But how to dispose whole solver?

When calling solver.Dispose(), you are calling this method:
```
public void Dispose()
{
    if (_isDisposed) return;
    foreach (var body in Bodies)
    {
        _world.RemoveRigidBody(body);
        body.Dispose();
    }
    foreach (var shape in _shapes)
    {
        shape.Dispose();
    }
    _world.Dispose();
    _broadphase.Dispose();
    _dispatcher.Dispose();
    _configuration.Dispose();
    _isDisposed = true;
}
```
So that's exactly what this method does: it disposes the objects inside the solver.

The solver object itself is a regular .NET object, so the .NET runtime automatically knows how and when to free the memory allocated to it. What the .NET runtime doesn't know is that BulletSharp objects within the solver also allocate unmanaged memory in C++, which .NET has no control of. That is the reason why Dispose() must be called explicitly and why objects owning IDisposable objects must also implement IDisposable to ensure that Dispose() gets called on objects that allocate unmanaged resources.

Resource management is a bit tricky, but pretty much essential for a .NET developer to know.
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/dispose-pattern

**Comment by petrasvestartas** [comment]
Thanks I will try to read through the IDisposable use.

Now from time to time I get:
System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

In terms of simulation rigid bodies with holes like this:
https://www.youtube.com/watch?v=jCyLtFYTCD8

Is it needed special setup in BulletSharp?

Would it be possible to get an example how to setup a chain like this, when all elements are the same rings?

**Comment by AndresTraks** [comment]
When does the AccessViolationException happen? During StepSimulation?

GImpactTestDemo has exactly this type of chain.
https://github.com/AndresTraks/BulletSharpPInvoke/blob/master/BulletSharp/demos/GImpactTestDemo/GImpactTestDemo.cs

**Comment by petrasvestartas** [comment]
Thanks for the references,

1.

Regarding error I forgot to dispose objects, now I did not get it anymore, I declare solver with like this, before running simulation. Which I do not know if it safe but so far so good. In the Rhino UI, I have boolean button to initialize an run BulletSharp solver:

**Edit: not stopping solver and running stepsimulation for 15 minutes gave the same error of memory**

            if (!this.reset) {

                //Initialize solver
                if (solver != null) {
                    Rhino.RhinoApp.WriteLine("C++ disposed");
                    solver.Dispose();
                    solver = new BulletPhysics.Solver(boxDimensions, positions, inertia);
                } else {
                    solver = new BulletPhysics.Solver(boxDimensions, positions, inertia);
                    Rhino.RhinoApp.WriteLine("C++ not disposed");
                }

            } else {
               solver.StepSimulation();
                //and retrieve the geometry 
             }

2.

I tried to check matrix transformation line  by line and it seems right, when change from row to collumns?
Can it be that rotations in z and x and y are totally different between bullet and rhino? O normally the order is the same? 

![rotations](https://user-images.githubusercontent.com/18013985/39004293-4cb55ce4-43fd-11e8-8b16-a3e32efd71b7.png)

https://www.youtube.com/watch?v=CBMTaAYjCVo&feature=youtu.be

3.

Probably I am annoying with all my questions, but how can I add object rotated, this line only moves object, but how to rotate for instance in 30 degrees as initial position?
    var box = CreateDynamicBody(boxShape, 1, BulletSharp.Math.Matrix.Translation(1, 10, 0), inertia);

**Comment by AndresTraks** [comment]
Can you share the two files again? I don't see anything wrong except that the motion state objects haven't been disposed. But I don't think that would cause an exception.

For rotation, multiply the translation matrix by some rotation matrix:
`BulletSharp.Math.Matrix.RotationX((float)Math.PI / 6) * BulletSharp.Math.Matrix.Translation(1, 10, 0)`

Rotation * translation means rotate and then translate.
Translation * rotation means translate and then rotate.

**Comment by petrasvestartas** [comment]
These are the files attached. 

BulletPhysicsGHComponent is Rhino interface.
[BulletPhysicsGHComponent.txt](https://github.com/AndresTraks/BulletSharpPInvoke/files/1931850/BulletPhysicsGHComponent.txt)

Solver.txt is the class you showed before. 
[Solver.txt](https://github.com/AndresTraks/BulletSharpPInvoke/files/1931851/Solver.txt)

I am still struggling to understand the transformations. To check whether they are correct I would like to retrieve each vertex  position of each rigid body to see whether there are any differences.


After step simulation, I loop through every rigid body.
Instead of using transformations just to check whether I made mistake, I would like to display rigid bodies vertex positions, encase of box shape I mean 8 vertex point of each box.
Is there any point location property like this: 
body.vertices.X,
body.vertices.Y,
body.vertices.Z ?
Each body is constructed from BoxShape class.

                foreach (RigidBody body in solver.Bodies) {
                    //how can I retrieve each body vertex positions
                    //is there something like body.vertices.X,body.vertices.Y,body.vertices.Z
                 }

**Comment by AndresTraks** [comment]
In general, you wouldn't get the locations of individual vertices from the physics engine, because it's much more efficient to take the transformation of a body and apply it to the geometry that you already know that the body has.

What you could do is use a debug drawer and assign it to World.DebugDrawer. If you override the DrawLine method and call world.DebugDrawWorld(), you get a list of all lines of all bodies. That is how the wireframe is created when you press F3 in BulletSharp demos.
```
public sealed class LineDebugger : DebugDraw
{
    public override DebugDrawModes DebugMode { get; set; } = DebugDrawModes.DrawWireframe;

    public override void Draw3dText(ref Vector3 location, string textString)
    {
        throw new NotImplementedException();
    }

    public override void DrawLine(ref Vector3 from, ref Vector3 to, ref Vector3 color)
    {
        // Render line (from, to)
    }

    public override void ReportErrorWarning(string warningString)
    {
        throw new NotImplementedException();
    }
}

_world.DebugDrawer = new LineDebugger();
```
Also, you can figure out the shape of the bodies by looking at body.CollisionShape.
```
var boxShape = body.CollisionShape as BoxShape;
if (boxShape != null)
{
	Vector3 halfSize = boxShape.HalfExtentsWithMargin;
	Box b = new Box(Plane.WorldXY, new Interval(-halfSize.X, halfSize.X), new Interval(-halfSize.Y, halfSize.Y), new Interval(-halfSize.Z, halfSize.Z));
}
```

**Comment by petrasvestartas** [comment]
Hi, How exactly can I attach DebugDrawer to retrieve all the lines? _world.DebugDraw() is void and I would like to ask how to return geometry collection?

What I did I simply created in visual studio LineDebugger class you posted above.


Then in the solver class I write this:

     public sealed class Solver : IDisposable {
           public Solver(float[] boxDimensions, List<float[]> positions, bool inertia = true) {
                 _world.DebugDrawer = new LineDebugger();
                  ....
                  //Add all rigid bodies and ground
                  .... 
                  _world.DebugDrawWorld();

        }

     ...

    }

**Comment by petrasvestartas** [comment]
I think I figured out the rotations, the way I solved it was just shuffling rotation list until it worked.. .ech 
I used genetive algorithm to find the best fitting shuffled parameters enough stupid solution made a good guess...
