### ISSUE TITLE
System.NullReferenceException BulletSharpTest

### ISSUE THREAD

**Issue by CorvoOrc** [AndresTraks/BulletSharpPInvoke#44]
Hi,
Im tried check my compilation libbulletc.dll successfull and run BulletSharpTest. In TestGCCollection()->...->NeedsCollision(ContancSensorCallback.cs)->CollisionObject.cs
function public bool CheckCollideWithOverride(CollisionObject co)
{
		return btCollisionObject_checkCollideWithOverride(Native, co.Native);
}

Im got exception NullReferencesException because **co** is null.

When Im commented TestContactTest(dynamicObject, dynamicObject2); function in TestGCCollection() function im got 3 fail tests but success processing with "Finished!" message.

Its my mistake with bad compilation libbulletc.dll or something else?

**Comment by AndresTraks** [comment]
I get that too.
It was probably because of https://github.com/AndresTraks/BulletSharpPInvoke/commit/3268e912b5c6bd1982137248acd7e338cb5b08d3, but I'm not sure yet.

**Comment by AndresTraks** [comment]
Fixed in https://github.com/AndresTraks/BulletSharpPInvoke/commit/9b6b9cea17a78cb10c566cbe2c9269948d31cd96.
Thanks!

**Comment by CorvoOrc** [comment]
Thanks for u support!
