### ISSUE TITLE
Demo Objects in red color what value is used ?

### ISSUE THREAD

**Issue by petrasvestartas** [AndresTraks/BulletSharpPInvoke#47]
Hi,

In demo simulations, when objects do not move/not colliding, they are colored in red.

What value do you use to determine this?

**Comment by AndresTraks** [comment]
obj.ActivationState
https://github.com/AndresTraks/BulletSharpPInvoke/blob/adb147cb93408a06f01f33d2ccb00144e3dbaf16/BulletSharp/demos/DemoFramework/Graphics/OpenTK/MeshFactory.cs#L314
