### ISSUE TITLE
No easy way to get the ragdoll part transform rotation of the parent part

### ISSUE THREAD

**Issue by anchurcn** [AndresTraks/BulletSharpPInvoke#52]
I want to bind a model to the ragdoll and set the bone position and rotation from the ragdoll's part transform. For example, the elbow rotation should relative to arm coordinates. My English is not that good, sorry. Appreciate for reply.

**Comment by AndresTraks** [comment]
Objects in Bullet only use world coordinates, so it's not an issue in Bullet/BulletSharp, but rather a question to ask in the [PyBullet forum](https://pybullet.org/Bullet/phpBB3/).

I think the idea is to multiply the world transform of the body part with the inverted world transform of its parent. See [here](https://pybullet.org/Bullet/phpBB3/viewtopic.php?t=8881).
