### ISSUE TITLE
Unable to compile libbulletc

### ISSUE THREAD

**Issue by publicENEMY** [AndresTraks/BulletSharpPInvoke#6]
Error   1   error MSB6006: "cmd.exe" exited with code 3.    C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets  170 5   ZERO_CHECK
Error   2   error MSB6006: "cmd.exe" exited with code 3.    C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets  170 5   libbulletc

**Comment by AndresTraks** [comment]
Not sure what the error is, but try pulling the last commit. I've resolved some conflicts with CMake.

**Comment by publicENEMY** [comment]
tried latest commit. still have errors, but different. here are the error

Error   75  error LNK1104: cannot open file 'BulletCollision_Debug.lib' e:\Users\iJam\Source\Repos\BulletSharpPInvoke\libbulletc\LINK   libbulletc

**Comment by AndresTraks** [comment]
Bullet should be compiled as described in the build instructions of BulletSharp. Since libbulletc has a VS2010 project, you need to set the build directory of bullet3 in CMake to ".../bullet3/msvc/2010". Then libbulletc should find the .lib files in bullet3/msvc/2010/lib/Debug.

**Comment by AndresTraks** [comment]
Here are the build instructions for BulletSharpPInvoke:
https://github.com/AndresTraks/BulletSharpPInvoke/wiki/Build-Instructions

**Comment by publicENEMY** [comment]
Thanks for the build instructions. Much appreciated. :)
