### ISSUE TITLE
Multithreaded rayTest

### ISSUE THREAD

**Issue by odydoum** [AndresTraks/BulletSharpPInvoke#63]
I am trying to fire some thousands of raycasts in parallel using c#. Although bullet's rayTest method is supposed to be thread safe (the author mentioned that on the bullet forums), after a lot of failed experiments I get a lot of false negatives, i.e rays that should hit sometimes report a miss. The serial version of my code works as expected.

Has anybody managed to fire multiple raycasts in parallel using this port?

**Comment by odydoum** [comment]
I am so sorry, apparently the rayTest method is not threadsafe if we don't build with the BULLET2_MULTITHREADING cmake option enabled (In the wiki's build instruction it is incorrectly listed as BULLET2_USE_THREAD_LOCKS). I was using my own custom built version so enabling multithreading and rebuilding as per the wiki instructions fixed my issue.

**Comment by AndresTraks** [comment]
Right, it looks like the option was renamed in June.
I'll fix that.
