### ISSUE TITLE
"Bullet object already initialized" exception at GhostObject creation

### ISSUE THREAD

**Issue by EugenyN** [AndresTraks/BulletSharpPInvoke#81]
Hello. please add `: base(ConstructionInfo.Null)`  to GhostObject ctor, otherwise we have "Bullet object already initialized." exception when creating a GhostObject 

https://github.com/AndresTraks/BulletSharpPInvoke/blob/65782433d500e3bdd4059ed0288a604a2b7c478c/BulletSharp/Collision/GhostObject.cs#L17

**Comment by AndresTraks** [comment]
Fixed.
Thanks!
